spring:
  application:
    name: item-service
    
#server:
#  port: 8001

eureka:
  client:
    service-url:
      #结合云服务才能设置其它选项,否则只能是defaultZone
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
rabbitmq:
    host: 192.168.247.132
    port: 5672
    username: admin
    password: admin
    
      
---
spring:
  profiles: item1
  
server:
  port: 8003
---
spring:
  profiles: item2

server:
  port: 8002